### ISSUE TITLE
Compiler error 1.2.2 CocoaPod in Xcode 6.0 iOS SDK

### ISSUE THREAD

**Issue by jamiebullock** [Tricertops/KeepLayout#47]
Compiling the 1.2.2 CocoaPod in Xcode 6.0 using the iOS 8.0 SDK, I get the following errors:

> ../KeepTypes.h:25:28: Expression is not an integer constant expression
> ../KeepTypes.h:26:24: Expression is not an integer constant expression
> ../KeepLayout/Sources/KeepTypes.h:27:23: Expression is not an integer constant expression
> ../KeepTypes.h:28:27: Expression is not an integer constant expression

This is because of the following code:

```
typedef enum : NSInteger {
    KeepPriorityRequired = UILayoutPriorityRequired,
    KeepPriorityHigh = UILayoutPriorityDefaultHigh,
    KeepPriorityLow = UILayoutPriorityDefaultLow,
    KeepPriorityFitting = UILayoutPriorityFittingSizeLevel,
} KeepPriority;
```

Here the `UIlayout` values are variables of type `static const UILayoutPriority` and therefore not legal (an integer literal is required).

Maybe this is already fixed in the git repository, otherwise I could submit a fix via pull request.

**Comment by PaulLafitskyi** [comment]
This issue still reproduce! 
![2016-09-23 15 11 38](https://cloud.githubusercontent.com/assets/8931303/18785291/17fbc2ca-81a0-11e6-8415-4e774ec6e96d.png)

**Comment by Tricertops** [comment]
@PaulLafitskyi Use the latest version, not CocoaPods version.
