### ISSUE TITLE
Update the version in cocoapods

### ISSUE THREAD

**Issue by K-Be** [Tricertops/KeepLayout#61]
I am going to use KeepLayout through Cocoapods, but in Cocoapods the last version is 1.2.2.
Can you update it?

**Comment by mattyohe** [comment]
@iMartinKiss It would be nice to address this as we have a internal pod that uses KeepLayout as a dependency. Dependencies in podspecs cannot reference specific git commits when specified.

Is there something I can do to help you push updates to the trunk?

**Comment by iMartinKiss** [comment]
You are being limited by your dependency manager. I have no interest to actively support CocoaPods.

But don’t worry, Block-KVO is not actively developed any more. If there will be some commits, they will be just bug fixes. Maybe you will be interested in my other repo Objective-Chain, which is a successor to Block-KVO.

**Comment by mattyohe** [comment]
@iMartinKiss Well, this was for KeepLayout...

Do you have any recommendations as to which dependency manager I should be using? You don't seem to support Carthage either.

**Comment by iMartinKiss** [comment]
Oops, sorry 😊 I’m replying from email and didn’t notice the subject. This same topic ongoing in Block-KVO too.

I have a podspec file in all repos. There was a time when I used to push new versions to CocoaPods trunk, but it was pretty annoying. Yes, they changed it to some command-line tool, but I never used CocoaPods myself. I don’t use Carthage neither.

I’m tagging commits with versions (mostly). You should use dependency manager that can handle git tags. If there is any.

If supporting Carthage means just adding Framework target, I might do this. Or someone who actualy uses Carthage will make a pull request.

**Comment by aspcartman** [comment]
Just update a podspec file and upload it. Also you can just fork this repo, tag it, update a cocoapod and use\post it. I have no idea why @iMartinKiss would not want to maintain a cocoapodspec since it’s just a couple of clicks.

**Comment by mattyohe** [comment]
@aspcartman Yeah, I think we're going to dump this library anyway. Really silly not to support any means of dependency management, but c'est la vie.
