### ISSUE TITLE
Migration to Swift

### ISSUE THREAD

**Issue by Tricertops** [Tricertops/KeepLayout#77]
Swift is the long-term plan of all Objective-C projects. Unfortunatelly, it seems like it’s not possible to make KeepLayout feel good in both languages at once. Transition to complex numbers as priorities broke Swift compatibility and adopting protocols (a proposed improvement) would break Objective-C compatibility.

I can imagine parallel development of Objective-C branch and Swift branch during transitioning period (years). This way, the Swift part would be free to diverge far into an arcane world of structs, protocols and crazy operators without carrying the Objective-C baggage.

I don’t plan to invest my time to this in near future, so I encourage users of KeepLayout to fork the project and experiment with Swift, as you wish. I would be happy to merge good ideas back to this main repo.

**Comment by Tricertops** [comment]
The optional priorities could be improved using protocols:

```swift
protocol KeepValue {
    var keepPrioritizedValue: KeepPrioritizedValue { get }
}

extension Double: KeepValue {
    var keepPrioritizedValue: KeepPrioritizedValue {
        return KeepPrioritizedValue(value: self, priority: 1000)
    }
}

struct KeepPrioritizedValue: KeepValue {
    let value: Double
    let priority: UILayoutPriority
    
    var keepPrioritizedValue: KeepPrioritizedValue { return self }
}

func KeepHigh(value: Double) -> KeepValue {
    return KeepPrioritizedValue(value: value, priority: UILayoutPriorityDefaultHigh)
}
```

Usage would then be:

```swift
var constraint: KeepValue
constraint = 10
constraint = KeepHigh(10)
```

**Comment by Tricertops** [comment]
I made the first step towards Swift future. I brought the Swift API on par with Objective-C API using the above approach. The usage is now identical, but uses completely different type systems.

```objc
// Objective-C
view.keepWidth.equal = 100;
```
```swift
// Swift
view.keepWidth.equal = 100
```

**Comment by AncAinu** [comment]
Any way that you do a swift 3.0 branch @Tricertops ?
I tried but I couldn't figure out one error given by the compiler "value use within it's own type"

**Comment by Tricertops** [comment]
@AncAinu I looked into this and it seems like a bug in Swift. However, I found a [workaround](https://github.com/Tricertops/KeepLayout/blob/swift-3/Sources/KeepLayout.swift#L123) and it’s now available on [`swift-3` branch](https://github.com/Tricertops/KeepLayout/tree/swift-3).

**Comment by AncAinu** [comment]
@Tricertops awesome workaround lol
