### ISSUE TITLE
iOS 10 issue with animations

### ISSUE THREAD

**Issue by AncAinu** [Tricertops/KeepLayout#82]
It seems that in iOS10, animations doesn't work properly.

What doesn't work:

```
    [myView keepAnimatedWithDuration:0.6 layout:^{
			view.keepTopInset.equal = 0;
			blurredView.alpha = 1;
		}]
```

or

```
    [myView keepAnimatedWithDuration:0.6 layout:^{
			view.keepTopInset.equal = 0;
			blurredView.alpha = 1;
			[view layoutIfNeeded];
		}]
```

What works:

```
    [myView keepAnimatedWithDuration:0.6 layout:^{
			view.keepTopInset.equal = 0;
			blurredView.alpha = 1;
			[self.view layoutIfNeeded]; // Superview of myView
		}]
```

**Comment by AncAinu** [comment]
I must precise, it's not with iOS 10, it's when compiling with SDK 10 (with latest Xcode 8)

**Comment by Tricertops** [comment]
Are you sure your code worked on iOS 9? The receiver of the `keepAnimated...` method should be the view that contains all of the animated views.

Can you describe your view hierarchy?

**Comment by AncAinu** [comment]
Yes it was working on iOS9 (well with SDK9) and the view receiving the keep animated is actually the one animated (sorry my example is wrong on that).
You are right it's probably my own code which is wrong, but still it was working before :D

**Comment by Tricertops** [comment]
iOS 10 probably changed some behavior of constraints or somethign like that.

There is an old saying: If re-layouting a view doesn’t work, try its superview :)
