### ISSUE TITLE
Align view1.center.y to view2.center.y + constant?

### ISSUE THREAD

**Issue by gerchicov-bp** [Tricertops/KeepLayout#83]
There are a lot of methods but no one allows to setup center.x/center.y separately for 2 defined views.

**Comment by Tricertops** [comment]
Did you try this one?

    view1.keepHorizontalAlignTo(view2).equal = constant

**Comment by gerchicov-bp** [comment]
It seems to be ok but unfortunately my chief forced me to replace KeepLayout with standard library calls. So I haven't a possibility to check it.
Anyways name "keepHorizontalAlignTo" confuses a programmer. Consider to change it to something more similar to "center.y" please

**Comment by Tricertops** [comment]
Yeah, standard AutoLayout API improved significantly in latest releases, so there is less need for 3rd party libs.
