### ISSUE TITLE
why wrong?

### ISSUE THREAD

**Issue by hongzhewudi** [Tricertops/KeepLayout#84]
lb_job.keepHeight.equal=KeepHigh(20);  yes? too long ,only 20 ,yes? how to do ?

**Comment by hongzhewudi** [comment]
I use PodFile, it is wrong that lb_job.keepHeight.equal=20,why ?

**Comment by Tricertops** [comment]
Sorry, could you please improve your question? I don’t understand.

**Comment by hongzhewudi** [comment]
I am very sad, I am Chinese, English is not good, how do I describe my problem?

**Comment by hongzhewudi** [comment]
我好伤心啊，我是中国人，英文讲的不好，我要怎么描述我的问题呢？

**Comment by hongzhewudi** [comment]
我用CocoaPods管理这个keeplayout，但是好郁闷的是UILabel高度不能随着文字的增多而自动变高，这个有办法吗？
