### ISSUE TITLE
Crash using keepHeight after upgrade to 1.7.1

### ISSUE THREAD

**Issue by ludovic-coder** [Tricertops/KeepLayout#89]
I just update my Pod to  KeepLayout 1.7.1. 
This line make the app crashed:

`_view.keepHeight.equal = KeepRequired(0);`

It can be reproduce for every view.

**Here the trace:**

> *** Assertion failure in -[UIView(KeepLayout) keep_selfAttributeForSelector:creationBlock:](), /Users/app/app/Pods/KeepLayout/Sources/KeepView.m:32
> *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Keep Layout: '
> *** First throw call stack:
> (0x186b33d38 0x186048528 0x186b33c0c 0x1874c2c90 0x102f086e8 0x102f09c20 0x102f0ac14 0x102950134 0x18ff428a4 0x18ff427d4 0x1029e1070 0x18ffb2050 0x1901a5898 0x1901aa6e4 0x190438454 0x1907081f0 0x1904380b8 0x190438928 0x190ba16e8 0x190ba158c 0x19091d9c0 0x190ab2fc8 0x19091d870 0x190707850 0x1901a8e28 0x1905ac6ec 0x1891d5768 0x1891de070 0x1038ad45c 0x1038b9b74 0x189209a04 0x1892096a8 0x189209c44 0x186adc358 0x186adc2d8 0x186adbb60 0x186ad9738 0x1869fa2d8 0x18888bf84 0x18ffa6880 0x102908058 0x18651e56c)
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Tricertops** [comment]
Sorry for that, fixed in latest commit.

**Comment by ludovic-coder** [comment]
@Tricertops Thanks for your very good work!

**Comment by ludovic-coder** [comment]
@Tricertops Finally, it"s still happening after pod update

**Comment by Tricertops** [comment]
I’m double sorry for that, I forgot to commit and push a better fix.

**Comment by ludovic-coder** [comment]
Ahah no problem, I believed it was a good idea to :)
