### ISSUE TITLE
Crash in the new version

### ISSUE THREAD

**Issue by nickbit** [Tricertops/KeepLayout#90]
Hi,
I keep getting a crash in the line changed in the last commit.
Please check.

> 2017-09-30 11:42:17.414204+0300 Live[22238:13746247] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Keep Layout: '
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x000000010ac261cb __exceptionPreprocess + 171
> 	1   libobjc.A.dylib                     0x000000011104bf41 objc_exception_throw + 48
> 	2   CoreFoundation                      0x000000010ac2b362 +[NSException raise:format:arguments:] + 98
> 	3   Foundation                          0x000000010c0dc523 -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
> 	4   KeepLayout                          0x000000010c6f6e8c -[UIView(KeepLayout) keep_selfAttributeForSelector:creationBlock:] + 1340
> 	5   KeepLayout                          0x000000010c6f8253 -[UIView(KeepLayout) keep_dimensionForSelector:dimensionAttribute:name:] + 1619
> 	6   KeepLayout                          0x000000010c6f928b -[UIView(KeepLayout) keepHeight] + 75
> 	7   Live                                0x000000010782dfb5 -[FLCImageBasePopup layoutUI] + 917
>

**Comment by Tricertops** [comment]
Ah, sorry. I think I’m going to delete that assert.

**Comment by Tricertops** [comment]
Did you find more exact reason why this failed?

I removed this assert from code.
